export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const RESET_ERRORS = 'RESET_ERRORS'

export const USER_REQUEST = 'USER_REQUEST'
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_ERROR = 'USER_ERROR'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'

export const CONVERSATION_REQUEST = 'CONVERSATION_REQUEST'
export const CONVERSATION_SUCCESS = 'CONVERSATION_SUCCESS'
export const CONVERSATION_ERROR = 'CONVERSATION_ERROR'
export const CONVERSATION_SELECT = 'CONVERSATION_SELECT'
export const CONVERSATION_ADD_MESSAGE = 'CONVERSATION_ADD_MESSAGE'
export const CONVERSATION_CREATED = 'CONVERSATION_CREATED'
export const CONVERSATION_ADD = 'CONVERSATION_ADD'
